import type { NextPage } from 'next'
import Head from 'next/head'
import { Code, Stack } from '@chakra-ui/react'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Stack direction='row'>
        <Code>console.log(welcome)</Code>
        <Code colorScheme='red'>var chakra = awesome!</Code>
      </Stack>
      </main>
    </div>
  )
}

export default Home
